In [1]:
from sklearn.neural_network import MLPClassifier  # Importa o MLPClassifier da biblioteca scikit-learn
from sklearn import datasets  # Importa o módulo de conjuntos de dados da biblioteca scikit-learn

# Carrega o conjunto de dados Iris
iris = datasets.load_iris()


In [47]:
#entradas = iris.data  # Atribui os dados de entrada do conjunto de dados Iris à variável 'entradas'
#saidas = iris.target  # Atribui os rótulos/classes do conjunto de dados Iris à variável 'saidas'


## Transformando lista em df

In [2]:
import pandas as pd

df = pd.DataFrame(iris.data, columns=['larg_sep', 'comp_sep', 'larg_pet', 'comp_pet'])
df['classe'] = iris.target

print(df)


     larg_sep  comp_sep  larg_pet  comp_pet  classe
0         5.1       3.5       1.4       0.2       0
1         4.9       3.0       1.4       0.2       0
2         4.7       3.2       1.3       0.2       0
3         4.6       3.1       1.5       0.2       0
4         5.0       3.6       1.4       0.2       0
..        ...       ...       ...       ...     ...
145       6.7       3.0       5.2       2.3       2
146       6.3       2.5       5.0       1.9       2
147       6.5       3.0       5.2       2.0       2
148       6.2       3.4       5.4       2.3       2
149       5.9       3.0       5.1       1.8       2

[150 rows x 5 columns]


## Padronização / Normalização

In [3]:
import pandas as pd
import numpy as np

def normalizar(x): #x será uma lista de valores numéricos
  return (x - np.min(x))/(np.max(x) - np.min(x))

def padronizar(x):
  return (x -np.mean(x))/np.std(x)


from scipy.stats import shapiro
# Verificar normalidade usando o teste de Shapiro-Wilk
def verifica_normalidade(dataframe, coluna):
    coluna_data = dataframe[coluna]
    # Realizar o teste de Shapiro-Wilk
    statistic, p_valor = shapiro(coluna_data)
    # Definir o nível de significância
    nivel_significancia = 0.1
    # Verificar se a hipótese nula de normalidade pode ser rejeitada
    if p_valor > nivel_significancia:
        print(f"A coluna '{coluna}' segue uma distribuição normal")
        return True
    else:
        print(f"A coluna '{coluna}' não segue uma distribuição normal")
        return False


In [54]:
# Chamando a função para verificar normalidade
for coluna in df.drop('classe', axis=1).columns:#['larg_sep', 'comp_sep', 'larg_pet', 'comp_pet']
  if verifica_normalidade(df, coluna):
    df[coluna] = padronizar(df[coluna])#se for distribuição normal, padroniza
  else:#senão, normaliza
    df[coluna] = normalizar(df[coluna])

A coluna 'larg_sep' não segue uma distribuição normal
A coluna 'comp_sep' segue uma distribuição normal
A coluna 'larg_pet' não segue uma distribuição normal
A coluna 'comp_pet' não segue uma distribuição normal


In [55]:
import pandas as pd
import numpy as np

def normalizar(x): #x será uma lista de valores numéricos
  return (x - np.min(x))/(np.max(x) - np.min(x))

def padronizar(x):
  return (x -np.mean(x))/np.std(x)

In [63]:
for coluna in df('larg_sep', 'comp_sep', 'larg_pet', 'comp_pet').columns:
    if verifica_normalidade(df, coluna):
        df[coluna] = padronizar(df[coluna])
    else:
        df[coluna] = normalizar(df[coluna])

TypeError: 'DataFrame' object is not callable

In [6]:
print(entradas)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
print(saidas)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
redeneural = MLPClassifier(verbose=True,  # Define se o modelo irá imprimir mensagens de progresso durante o treinamento. Neste caso, definido como True para exibir mensagens.
                           max_iter=10000,  # Número máximo de iterações (épocas) durante o treinamento da rede neural. Aqui definido como 10000.
                           tol=0.000001,  # Tolerância para o critério de parada do treinamento. O treinamento irá parar se a perda for menor que esse valor. Aqui definido como 0.000001.
                           activation='relu',  # Função de ativação usada nas camadas ocultas da rede neural. 'relu' é uma função de ativação comumente utilizada.
                           hidden_layer_sizes=(4,4),  # Tamanhos das camadas ocultas da rede neural. Este parâmetro não está definido corretamente.
                           learning_rate_init=0.0001  # Taxa de aprendizado inicial da rede neural. Aqui definida como 0.0001.
                           )


In [18]:
redeneural.fit(entradas, saidas)

Iteration 1, loss = 1.28983430
Iteration 2, loss = 1.28928329
Iteration 3, loss = 1.28873315
Iteration 4, loss = 1.28818390
Iteration 5, loss = 1.28763555
Iteration 6, loss = 1.28708811
Iteration 7, loss = 1.28654232
Iteration 8, loss = 1.28599815
Iteration 9, loss = 1.28545498
Iteration 10, loss = 1.28491280
Iteration 11, loss = 1.28437162
Iteration 12, loss = 1.28383143
Iteration 13, loss = 1.28329225
Iteration 14, loss = 1.28275408
Iteration 15, loss = 1.28221692
Iteration 16, loss = 1.28168111
Iteration 17, loss = 1.28114643
Iteration 18, loss = 1.28061280
Iteration 19, loss = 1.28008022
Iteration 20, loss = 1.27954869
Iteration 21, loss = 1.27901821
Iteration 22, loss = 1.27848889
Iteration 23, loss = 1.27796073
Iteration 24, loss = 1.27743362
Iteration 25, loss = 1.27690758
Iteration 26, loss = 1.27638349
Iteration 27, loss = 1.27586141
Iteration 28, loss = 1.27534067
Iteration 29, loss = 1.27482094
Iteration 30, loss = 1.27430219
Iteration 31, loss = 1.27378443
Iteration 32, los

c:\ProgramData\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(4, 4), learning_rate_init=0.0001,
              max_iter=10000, tol=1e-06, verbose=True)

In [19]:
redeneural.predict([[6.7, 3.0, 5.2, 2.3]])

array([2])